# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile
PROJECT_DIR       = /home/babar/Documents/Robus/Node_programmer_2/Node_programmer_2
USER_LIB_PATH    =  /home/babar/src/Arduino/libraries
BOARD_TAG    = nano328
ARDUINO_LIBS += SoftwareSerial
# GPS pin Affichage


#MONITOR_PORT = /dev/ttyUSB0
#MONITOR_BAUDRATE  = 115200
include /usr/share/arduino/Arduino.mk